Controllers/AppUserListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomIdentity.Data;
using CustomIdentity.Models;

namespace CustomIdentity.Controllers
{
    public class AppUserListsController : Controller
    {
        private readonly AppDbContext _context;

        public AppUserListsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: AppUserLists
        public async Task<IActionResult> Index()
        {
         
                    
            return View(await _context.AppUserLists.ToListAsync());
        }

        // GET: AppUserLists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appUserList = await _context.AppUserLists
                .FirstOrDefaultAsync(m => m.id == id);
            if (appUserList == null)
            {
                return NotFound();
            }

            return View(appUserList);
        }

        // GET: AppUserLists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AppUserLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Mobile,Email,Address")] AppUserList appUserList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appUserList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appUserList);
        }

        // GET: AppUserLists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            bool canEdit = true; // Example condition

            ViewBag.IsEditable = canEdit;
            if (id == null)
            {
                return NotFound();
            }

            var appUserList = await _context.AppUserLists.FindAsync(id);
            if (appUserList == null)
            {
                return NotFound();
            }
            return View(appUserList);
        }

        // POST: AppUserLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Mobile,Email,Address")] AppUserList appUserList)
        {
            if (id != appUserList.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appUserList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppUserListExists(appUserList.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appUserList);
        }

        // GET: AppUserLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appUserList = await _context.AppUserLists
                .FirstOrDefaultAsync(m => m.id == id);
            if (appUserList == null)
            {
                return NotFound();
            }

            return View(appUserList);
        }

        // POST: AppUserLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appUserList = await _context.AppUserLists.FindAsync(id);
            if (appUserList != null)
            {
                _context.AppUserLists.Remove(appUserList);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppUserListExists(int id)
        {
            return _context.AppUserLists.Any(e => e.id == id);
        }
    }
}

Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomIdentity.Data;
using CustomIdentity.Models;
using CustomIdentity.ViewModels;

namespace CustomIdentity.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly AppDbContext _context;

        public PropertiesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Properties
        public async Task<IActionResult> Index(string searchString)
        {
            var properties = await _context.Properties.ToListAsync();
            if (!string.IsNullOrEmpty(searchString))
            {
                properties = properties.Where(n => n.Property_Name.Contains(searchString)).ToList();
            }
            return View(properties);
            //return View(await _context.Properties.ToListAsync());
        }

        // GET: Properties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Properties
                .FirstOrDefaultAsync(m => m.Property_ID == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // GET: Properties/Create
        public IActionResult Create()

        {
          
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Property_ID,Property_Name,Property_Type,Location,Size_SqFt,Price,Number_of_Bedrooms,Number_of_Bathrooms")] Property @property)
        {
            
            if (ModelState.IsValid)
            {
              
                _context.Add(@property);
                
               
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@property);
        }

        // GET: Properties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Properties.FindAsync(id);
            if (@property == null)
            {
                return NotFound();
            }
            return View(@property);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Property_ID,Property_Name,Property_Type,Location,Size_SqFt,Price,Number_of_Bedrooms,Number_of_Bathrooms")] Property @property)
        {
            if (id != @property.Property_ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@property);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyExists(@property.Property_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@property);
        }

        // GET: Properties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Properties
                .FirstOrDefaultAsync(m => m.Property_ID == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @property = await _context.Properties.FindAsync(id);
            if (@property != null)
            {
                _context.Properties.Remove(@property);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropertyExists(int id)
        {
            return _context.Properties.Any(e => e.Property_ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ifelse.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomIdentity.styles.css" asp-append-version="true" />
</head>
<body>
    <header >     
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-lightcoral border-bottom box-shadow mb-3" style="background-color: lavender">

            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: darkblue;font-weight: bold;font-style: italic;">ifelse property</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"> Home </a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="Index"> Manage Properties </a>

                            </li>
                        }
                        @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppUserLists" asp-action="Index"><UserList</a>
                        </li> *@
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" >
            &copy; 2025 - ifelse property - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>